[package]
name = "dds_manual_app"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dust_dds_derive = "0.12.0"
dust_dds = "0.5.0"
anyhow = "1.0"
warp = "0.3"
serde_json = "1.0"